### ISSUE TITLE
Error in read_wikitables2()

### ISSUE THREAD

**Issue by rporta23** [baumer-lab/wikitablr#17]
library(wikitablr)
read_wikitables2("https://en.wikipedia.org/wiki/List_of_colleges_and_universities_in_Massachusetts")
#> Error: Argument 1 must have names

**Comment by beanumber** [comment]
``` r
library(wikitablr)
read_wikitables2("https://en.wikipedia.org/wiki/List_of_colleges_and_universities_in_Massachusetts")
#> # A tibble: 3 x 6
#>   class           style          table          number retrieved           bytes
#>   <chr>           <chr>          <list>          <int> <dttm>              <dbl>
#> 1 wikitable sort… text-align:le… <df[,7] [103 …      1 2020-08-16 11:32:19 40504
#> 2 wikitable sort… text-align:le… <df[,2] [37 ×…      2 2020-08-16 11:32:19  7528
#> 3 wikitable sort… text-align:le… <df[,7] [96 ×…      3 2020-08-16 11:32:19 25624
```

<sup>Created on 2020-08-16 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by beanumber** [comment]
Are you sure that you are using the most recent version of `wikitablr`? What does `sessionInfo()` say?

**Comment by rporta23** [comment]
Is this the latest version: wikitablr_0.1.0.9003 ?
I also just tried reinstalling it and it said: 
> devtools::install_github("baumer-lab/wikitablr")
Skipping install of 'wikitablr' from a github remote, the SHA1 (c6c1e8a3) has not changed since last install.
  Use `force = TRUE` to force installation

So I'm pretty sure it's the latest version?

**Comment by niannucci** [comment]
updating all packages eliminated this issue for me

**Comment by rporta23** [comment]
I tried updating all of my packages and am now getting this error:

library(wikitablr)
presidents <- read_wikitables2("https://en.wikipedia.org/wiki/List_of_presidents_of_the_United_States_by_age")
Error: Problem with `mutate()` input `bytes`.
x unable to load shared object '/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/libs/Rcpp.so':
  dlopen(/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/libs/Rcpp.so, 6): Symbol not found: _EXTPTR_PTR
  Referenced from: /Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/libs/Rcpp.so
  Expected in: /Library/Frameworks/R.framework/Resources/lib/libR.dylib
 in /Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/libs/Rcpp.so
ℹ Input `bytes` is `purrr::map(table, lobstr::obj_size)`.
Run `rlang::last_error()` to see where the error occurred.

**Comment by beanumber** [comment]
@rporta23 you may need to:

1. restart R
2. reinstall `Rcpp`
3. maybe reinstall `dplyr`

Let me know if the problem persists.

**Comment by rporta23** [comment]
@beanumber
HI Ben,

I tried all of those things and am still getting the same error. 

-Rose
